spring:
  config:
    import:
      - classpath:application-secret.yml
  #
  #  datasource:
  #    url: ${url}
  #    username: ${username}
  #    password: ${password}
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      maximum-pool-size: 5

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace # TRACE Log? ?? ???? ??
